name: DangerFlutterLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2

      - name: setup Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable

      - name: pub get
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze > flutter_analyze_report.txt

      - name: setup ruby
        if: ${{ failure() }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: run danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5.0.1
        with:
          plugins_file: Gemfile
          install_path: vendor/bundle
          danger_file: Dangerfile
          danger_id: danger-pr
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.EKUSIADADUS_TOKEN }}